services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "NoweSilneHaslo123!"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Forge.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=TaskManagerDb;User Id=sa;Password=NoweSilneHaslo123!;TrustServerCertificate=True;MultipleActiveResultSets=true"
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  web:
    build:
      context: ./Forge.Web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  dbdata: